projects:
  app:
    schemaPath: ../service/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  prisma:
    schemaPath: service/generated/prisma.graphql
    extensions:
      prisma: prisma.yml
      codegen:
      - generator: prisma-binding
        language: js
        output:
          binding: ../service/generated/prisma.js
